apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-product-service
  namespace: insureflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-product-service
  template:
    metadata:
      labels:
        app: postgres-product-service
    spec:
      containers:
        - name: postgres-product-service
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: insureflow-secrets
                  key: postgres-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: insureflow-secrets
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: insureflow-secrets
                  key: postgres-password
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-product-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-product-service
  namespace: insureflow
spec:
  selector:
    app: postgres-product-service
  ports:
    - port: 5432